name: Setup GStreamer
description: Setup GStreamer by either downloading or building via Cerbero.
inputs:
  cerbero-repo:
    description: 'Repository to use for Cerbero'
    required: false
    default: https://gitlab.freedesktop.org/gstreamer/cerbero.git
  cerbero-ref:
    description: 'Ref to use for Cerbero'
    required: false
    default: main
  config:
    description: 'Name of the configuration file to use'
    required: false
  cerbero-args:
    description: 'Additional args to pass to Cerbero'
    required: false
    default: '--clocktime --timestamps'
  cerbero-package-args:
    description: 'Additional args to pass to Cerbero package'
    required: false
    default: ''
  cerbero-action-ref:
    description: 'Branch/tag/ref to use for cloning cerbero-action'
    required: false
    default: main
  cleanup:
    description: 'Whether to clean the Cerbero build directory'
    required: false
    default: 'true'
  no-cache:
    description: 'Whether to disable restoring from cache'
    required: false
    default: 'false'
  s3-download-paths:
    description: 'S3 paths to download from'
    required: false
  s3-upload-path:
    description: 'S3 path to upload to'
    required: false
  gst-plugins-rs-repo:
    description: 'Repository to use for gst-plugins-rs'
    required: false
  gst-plugins-rs-ref:
    description: 'Ref/tag to use for gst-plugins-rs'
    required: false
outputs:
  gstreamer-version:
    description: 'GStreamer version'
    value: ${{ steps.setup-action.outputs.gstreamer-version }}
  cerbero-short-sha:
    description: 'Short SHA of the Cerbero checkout'
    value: ${{ steps.setup-action.outputs.cerbero-short-sha }}
  install-dir:
    description: 'GStreamer install directory'
    value: ${{ steps.setup-action.outputs.install-dir }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      # Checkout the action so that when another repo uses this action,
      # the 'uses' will resolve to the actions contained in this repo.
      with:
        repository: laerdallabs/cerbero-action
        ref: ${{ inputs.cerbero-action-ref }}
        path: .ca
        fetch-depth: 1

    - name: Run Setup Action
      id: setup-action
      uses: ./.ca/.github/actions/setup
      with:
        cerbero-repo: ${{ inputs.cerbero-repo }}
        cerbero-ref: ${{ inputs.cerbero-ref }}
        cerbero-args: ${{ inputs.cerbero-args }}
        cerbero-package-args: ${{ inputs.cerbero-package-args }}
        config: ${{ inputs.config }}
        cleanup: ${{ inputs.cleanup }}
        no-cache: ${{ inputs.no-cache }}
        s3-download-paths: ${{ inputs.s3-download-paths }}
        s3-upload-path: ${{ inputs.s3-upload-path }}
        gst-plugins-rs-repo: ${{ inputs.gst-plugins-rs-repo }}
        gst-plugins-rs-ref: ${{ inputs.gst-plugins-rs-ref }}

    - name: Cleanup Cerbero
      if: ${{ always() && inputs.cleanup == 'true' }}
      shell: ${{ runner.os == 'Windows'  && 'msys2 -eo pipefail {0}' || 'bash' }}
      run: rm -rf cerbero
