name: Linux

on:
  workflow_dispatch:
    inputs:
      cerbero-repo:
        description: 'Repository to use for Cerbero'
        required: false
        default: https://github.com/blinemedical/cerbero.git
      cerbero-ref:
        description: 'Ref to use for Cerbero'
        required: false
        default: fixes-for-cerbero-action
      bootstrap-system:
        description: 'Bootstrap the system before building'
        required: false
        type: boolean
        default: true
      no-cache:
        description: 'Do not use cache when building'
        required: false
        type: boolean
        default: false

jobs:
  build:
    name: Build
    runs-on:
      group: larger-ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: build-gstreamer
        name: Build GStreamer
        uses: ./
        with:
          cerbero-repo: ${{ inputs.cerbero-repo }}
          cerbero-ref: ${{ inputs.cerbero-ref }}
          no-cache: ${{ inputs.no-cache == true }}
          bootstrap-system: ${{ inputs.bootstrap-system }}
