name: Windows

on:
  workflow_dispatch:
    inputs:
      cerbero-repo:
        description: 'Repository to use for Cerbero'
        required: false
        default: https://github.com/blinemedical/cerbero.git
      cerbero-ref:
        description: 'Ref to use for Cerbero'
        required: false
        default: 1.24-lldc
      no-cache:
        description: 'Do not use cache when building'
        required: false
        type: boolean
        default: false

jobs:
  build:
    name: Build
    runs-on:
      group: larger-windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: build-gstreamer
        name: Build GStreamer
        uses: ./
        with:
          cerbero-repo: ${{ inputs.cerbero-repo }}
          cerbero-ref: ${{ inputs.cerbero-ref }}
          cerbero-args: '--clocktime --timestamps -v visualstudio'
          config: 'win64.cbc'
          no-cache: ${{ inputs.no-cache == true }}
          cerbero-action-ref: ${{ github.ref }}
